title: >
  Support for joining minilaterals

#source: >
  #<b>Source:</b> Lorem ipsum

#notes: >
  #<b>Notes:</b> Lorem ipsum

subtitle: >
  Would you support or oppose Indonesia forming partnerships/minilaterals with other middle powers and neighbours depending on different issues and interests?

axes:
  minY:  0
  maxY: 10
  stepsY: 6
  rotateX: false
  percentage: false
  minorLines: false
  dotted: [] # Index of dotted gridlines
  reverse: false
  guideLine: null # value of optional horizontal line. set 'null' if disabled

series:
  -
    title: Year
    values:
      - 2011
      - 2012
      - 2013
      - 2014
      - 2015
      - 2016

  -
    title: Support
    color: "blue-100"
    widen: false
    dashed: true
    values:
      - 1
      - 1
      - 1
  -
    title: Oppose
    color: "orange"
    widen: false
    dashed: true
    values:
      - 1
      - 1
      - 1
  -
    title: Don’t know
    color: "grey"
    widen: false
    dashed: true
    values:
      - 1
      - 1
      - 1