title: >
  Effort to combat climate change

#source: >
  #<b>Source:</b> Lorem ipsum

#notes: >
  #<b>Notes:</b> Lorem ipsum

subtitle: >
  For each of these countries, do you think they have done too much, too little, or about the right amount in their effort to combat climate change?

axes:
  minX:  0
  maxX: 100
  stepsX: 6
  percentage: true
  minorLines: true
  dotted: [1,3,5,7,9,11,13] # Index of dotted gridlines
  reverse: false

series:
  -
    title: Country
    values:
      - United States
      - Indonesia
      - Japan
      - Australia
      - China
      - India

  -
    title: Too much
    color: "blue-100"
    values:
      - 25
      - 24
      - 22
      - 19
      - 18
      - 15

  -
    title: The right amount
    color: "grey"
    values:
      - 37
      - 37
      - 38
      - 33
      - 37
      - 29

  -
    title: Too little
    color: "orange"
    values:
      - 39
      - 39
      - 40
      - 48
      - 46
      - 56
