title: >
  Figure 3. Indonesian government’s infrastructure budget

source: >
  <strong>Source:</strong> Author’s calculation based on data from Indonesia’s Ministry of Finance and Bank Indonesia.

subtitle: >
  Trillion rupiah

charts:
  -
    #title: Urban population growth
    subtitle: Trillion rupiah
    scale:
      ticks: [8,7]
      minY: [0,0]
      maxY: [1200,25]
      datum: 0
    legend:
      - name: null
        scale: 0
      - name: Urban population (LHS)
        scale: 0
      - name: Annual change (RHS)
        scale: 1
      - name: UN projection
        scale: 1
