title: >
  Overall Economic Relationships Score

source: >
  <strong>Source:</strong> Lowy Institute (<a href="https://power.lowyinstitute.org/" target="_blank">Asia Power Index</a>)

#notes: >
  #<strong>Notes:</strong> data from January 2022

subtitle: >
  Chinese and US influence in Southeast Asian countries (2022)

axes:
  minY:  0
  maxY: 100
  stepsY: 9
  stepsX: 10
  rotateX: true
  percentage: false
  minorLines: true
  dotted: [1,2,3,4,5,6,7,8,9] # Index of dotted gridlines
  reverse: false
  guideLine: null # value of optional horizontal line. set 'null' if disabled

series:
  -
    title: Country
    values:
      - Brunei
      - Cambodia
      - Indonesia
      - Laos
      - Malaysia
      - Myanmar
      - Philippines
      - Singapore
      - Thailand
      - Vietnam
  -
    title: China
    color: "red"
    widen: false
    dashed: false
    values:
      - 84
      - 77
      - 80
      - 92
      - 78
      - 80
      - 73
      - 60
      - 64
      - 53

  -
    title: United States
    color: "highlight"
    widen: false
    dashed: false
    values:
      - 16
      - 23
      - 20
      - 8
      - 22
      - 20
      - 27
      - 40
      - 36
      - 47

