title: >
 Figure 10: General Assembly resolutions

#source: >
  #<b>Source:</b> Lorem ipsum

#notes: >
  #<b>Notes:</b> Lorem ipsum

subtitle: >
  Number of UN General Assembly resolutions mentioning China-promoted phrases

axes:
  minY:  0
  maxY: 12
  stepsY: 7
  rotateX: false
  percentage: false
  minorLines: true
  dotted: [] # Index of dotted gridlines
  reverse: false

series:
  -
    title: Year
    values:
      - 2000
      - 2001
      - 2002
      - 2003
      - 2004
      - 2005
      - 2006
      - 2007
      - 2008
      - 2009
      - 2010
      - 2011
      - 2012
      - 2013
      - 2014
      - 2015
      - 2016
      - 2017
      - 2018
      - 2019
      - 2020
      - 2021
      - 2022
  -
    title: Win-win cooperation
    color: "green"
    values:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 3
      - 2
      - 4
      - 4
      - 4
      - 3
      - 1
      - 0
  -
    title: Shared future
    color: "blue-100"
    values:
      - 2
      - 1
      - 1
      - 3
      - 3
      - 1
      - 2
      - 0
      - 2
      - 1
      - 2
      - 2
      - 2
      - 3
      - 1
      - 3
      - 2
      - 5
      - 3
      - 5
      - 4
      - 4
      - 3
  -
    title: Community of shared future
    color: "highlight"
    values:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 3
      - 2
      - 2
      - 1
      - 2
      - 0
  

