title: >
  Forecast GDP growth rates for year 2020

source: >
  <b>Source:</b> ??

notes: >
  <b>Notes:</b> Lorem ipsum

subtitle: ""

axes:
  max:  10 # ± max scale
  steps: 6  # steps per side
  percentage: true
  minorLines: true
  dotted: true
  reverse: true
  minInnerLabel: 2 # bars with lower absolute have value labels outside bar

series:
  -
    title: Categories
    values:
      - Bangladesh
      - India
      - Cambodia
      - Laos
      - Vietnam
      - Nepal
      - Myanmar
      - Philippines
      - China
      - Mongolia
      - Indonesia
      - Brunei
      - Malaysia
      - Sri Lanka
      - Thailand
      - New Zealand
      - Papua New Guinea
      - Pakistan
      - Australia
      - South Korea
      - United States
      - Taiwan
      - Russia
      - Singapore
      - Japan


  -
    title: Post COVID-19
    color: "orange"
    values:
      -  1.6
      - -3.2
      - -1.0
      -  1.0
      -  2.8
      -  1.8
      -  1.5
      - -1.9
      -  1.0
      - -0.5
      -  0.0
      -  1.3
      - -3.1
      - -3.2
      - -5.0
      - -8.9
      - -1.3
      - -2.6
      - -5.0
      - -1.2
      - -7.3
      - -4.0
      - -6.0
      - -3.5
      - -6.0


  -
    title: Pre COVID-19
    color: "dark"
    values:
      - 7.4
      - 7.0
      - 6.8
      - 6.5
      - 6.5
      - 6.3
      - 6.3
      - 6.2
      - 5.8
      - 5.4
      - 5.1
      - 4.7
      - 4.4
      - 3.5
      - 3.0
      - 2.7
      - 2.6
      - 2.4
      - 2.3
      - 2.2
      - 2.1
      - 1.9
      - 1.9
      - 1.0
      - 0.5
