title: >
  Source of Covid-19 pandemic

notes: >
  * When asked to nominate which country, 11.7% of respondents say China,
  whereas 0.2% say the United States.

subtitle: >
  From what you have seen or heard, which of the following do you think is the
  most likely cause of the Covid-19 pandemic?

axes:
  minX: 0
  maxX: 40
  stepsX: 5
  percentage: true
  minorLines: false
  dotted: [1, 3, 5, 7, 9, 11, 13] # Index of dotted gridlines
  reverse: false

series:
  - title: Category
    values:
      - An act of God
      - Human contact with an infected animal
      - A laboratory leak in a foreign country*
      - A domestic problem or issue
      - Don’t know

  - title: A lot of confidence
    color: "blue-100"
    values:
      - 37
      - 22
      - 12
      - 8
      - 19
