title: >
  Figure 3: Wages and profit shares of factor income

subtitle: >

source: >
  <b>Source:</b> Australian Bureau of Statistics

notes: >


charts:
  -
    title: >
      Comparing household and business debt
    scale:
      ticks: [10,10]
      minY: [20,50]
      maxY: [30,60]
    legend:
      - name: Profits share (LHS)
        scale: 0
      - name: Wages share (RHS)
        scale: 1
    colors:
      - "#002a45"
      - "#539ed4"
    axes:
      -
        title: Years
        values:
          - 1988
          - 1989
          - 1990
          - 1991
          - 1992
          - 1993
          - 1994
          - 1995
          - 1996
          - 1997
          - 1998
          - 1999
          - 2000
          - 2001
          - 2002
          - 2003
          - 2004
          - 2005
          - 2006
          - 2007
          - 2008
          - 2009
          - 2010
          - 2011
          - 2012
          - 2013
          - 2014
          - 2015
          - 2016
          - 2017
          - 2018
          - 2019

      -
        title: |
          %
        values:
          - [ 24.6, 54.0 ]
          - [ 24.2, 54.2 ]
          - [ 23.0, 55.4 ]
          - [ 22.4, 56.1 ]
          - [ 23.6, 55.1 ]
          - [ 25.1, 54.1 ]
          - [ 25.3, 54.5 ]
          - [ 25.2, 55.1 ]
          - [ 24.7, 55.6 ]
          - [ 24.0, 55.5 ]
          - [ 24.4, 55.3 ]
          - [ 24.5, 55.5 ]
          - [ 26.1, 54.9 ]
          - [ 24.9, 55.3 ]
          - [ 25.4, 54.4 ]
          - [ 26.2, 54.6 ]
          - [ 25.6, 54.3 ]
          - [ 26.3, 53.9 ]
          - [ 27.4, 53.7 ]
          - [ 27.1, 54.1 ]
          - [ 28.0, 52.7 ]
          - [ 28.1, 52.2 ]
          - [ 28.5, 52.1 ]
          - [ 28.6, 52.2 ]
          - [ 27.7, 53.3 ]
          - [ 27.6, 53.2 ]
          - [ 26.6, 53.5 ]
          - [ 25.1, 54.2 ]
          - [ 25.4, 54.1 ]
          - [ 27.5, 52.4 ]
          - [ 28.1, 52.3 ]
          - [ 29.1, 52.2 ]
