title: >
  Figure 3: Wages and profit shares of factor income

subtitle: >

source: >
  <b>Source:</b> Australian Bureau of Statistics

notes: >


charts:
  -
    title: >
      Comparing household and business debt
    scale:
      ticks: [7,7]
      minY: [0, 0]
      maxY: [60,60]
    legend:
      - name: Wages share
        scale: 0
      - name: Profits share
        scale: 0
    colors:
      - "#002a45"
      - "#539ed4"
    axes:
      -
        title: Years
        values:
          - 1988
          - 1989
          - 1990
          - 1991
          - 1992
          - 1993
          - 1994
          - 1995
          - 1996
          - 1997
          - 1998
          - 1999
          - 2000
          - 2001
          - 2002
          - 2003
          - 2004
          - 2005
          - 2006
          - 2007
          - 2008
          - 2009
          - 2010
          - 2011
          - 2012
          - 2013
          - 2014
          - 2015
          - 2016
          - 2017
          - 2018
          - 2019

      -
        title: |
          %
        values:
          - [ 54.0, 24.6 ]
          - [ 54.2, 24.2 ]
          - [ 55.4, 23.0 ]
          - [ 56.1, 22.4 ]
          - [ 55.1, 23.6 ]
          - [ 54.1, 25.1 ]
          - [ 54.5, 25.3 ]
          - [ 55.1, 25.2 ]
          - [ 55.6, 24.7 ]
          - [ 55.5, 24.0 ]
          - [ 55.3, 24.4 ]
          - [ 55.5, 24.5 ]
          - [ 54.9, 26.1 ]
          - [ 55.3, 24.9 ]
          - [ 54.4, 25.4 ]
          - [ 54.6, 26.2 ]
          - [ 54.3, 25.6 ]
          - [ 53.9, 26.3 ]
          - [ 53.7, 27.4 ]
          - [ 54.1, 27.1 ]
          - [ 52.7, 28.0 ]
          - [ 52.2, 28.1 ]
          - [ 52.1, 28.5 ]
          - [ 52.2, 28.6 ]
          - [ 53.3, 27.7 ]
          - [ 53.2, 27.6 ]
          - [ 53.5, 26.6 ]
          - [ 54.2, 25.1 ]
          - [ 54.1, 25.4 ]
          - [ 52.4, 27.5 ]
          - [ 52.3, 28.1 ]
          - [ 52.2, 29.1 ]
