title: >
  Warship tonnage launched 2016&#8288;–&#8288;2020

source: >
  <b>Source:</b> Lorem ipsum

notes: >
  <b>Notes:</b> Lorem ipsum

subtitle: >
  '000s TONNES

axes:
  minY:  0
  maxY: 600000
  stepsY: 7
  rotateX: false
  percentage: false
  minorLines: true
  dotted: [] # Index of dotted gridlines
  reverse: false

series:
  -
    title: Year
    values:
      - PLA Navy
      - US Navy
      - Quad navies
      - Indopacific democracies



  -
    title: PLA
    color: "red"
    values:
      - 632847
      - 0
      - 0
      - 0

  -
    title: Pacific Fleet
    color: "blue-100"
    values:
      - 0
      - 257155
      - 257155
      - 0
      
  -
    title: Rest of Fleet
    color: "blue-300"
    values:
      - 0
      - 171437
      - 0
      - 0

  -
    title: JPN
    color: "red-dark"
    values:
      - 0
      - 0
      - 51000
      - 51000
      
  -
    title: IND
    color: "orange"
    values:
      - 0
      - 0
      - 41624
      - 41624
      
  -
    title: AUS
    color: "teal-dark"
    values:
      - 0
      - 0
      - 51700
      - 51700
  
  -
    title: ROK
    color: "teal"
    values:
      - 0
      - 0
      - 0
      - 82378
      
  -
    title: PHL
    color: "yellow"
    values:
      - 0
      - 0
      - 0
      - 5200
