title: >
  Culture

source: >
  Source: XX

charts:
  -
    subtitle: >
      COVID-19 response: Proportion of better and worse performing countries by category
    scale:
      minY:  0
      maxY: 75
    axes:
      -
        title: Culture
        values:
          - Asian
          - Western
          - Other
      -
        title: Better performing
        values:
          - 67
          - 47
          - 44
      -
        title: Worse performing
        values:
          - 33
          - 53
          - 56
