list:
  - country: United States
    rank: 1
    rank2:
    trend: -1
    change: 75.9
  - country: China
    rank: 2
    rank2:
    trend: -1
    change: 72.9
  - country: India
    rank: 3
    rank2: 
    trend: -1
    change: 47.7
  - country: Russia
    rank: 4
    rank2:
    trend: -1
    change: 16.0
  - country: Japan
    rank: 5
    rank2: 1
    trend: 0
    change: 11.6
  - country: Indonesia
    rank: 6
    rank2: -1
    trend: 0
    change: 11.5
  - country: South Korea
    rank: 7
    rank2: 
    trend: 1
    change: 11.4
  - country: Pakistan
    rank: 8
    rank2: 
    trend: 1
    change: 11.3
  - country: Australia
    rank: 9
    rank2: 
    trend: 0
    change: 10.5
  - country: Vietnam
    rank: 10
    rank2: 
    trend: 0
    change: 6.9