title: >
  Proficiency of Chinese languages in the Australian Public Service

source: >
  <b>Sources</b><br>
  DFAT: Supplied by DFAT, current as at 17 Aug 2020<br>
  Defence: Supplied by the Department of Defence, 22 Aug 2020<br>
  Australian population: <a href="https://www.abs.gov.au/ausstats/abs@.nsf/Lookup/by%20Subject/2071.0~2016~Main%20Features~Cultural%20Diversity%20Article~60" target="_blank"><em>Cultural Diversity in Australia</em></a> (2016 ABS Census data)

notes: >
  <b>Notes:</b> Lorem ipsum

subtitle: >
  % of employees identified as proficient in Mandarin or Cantonese

axes:
  minX: 0
  maxX: 4
  stepsX: 5
  percentage: true
  minorLines: false
  dotted: [] # Index of dotted gridlines
  reverse: true

series:
  -
    title: Department
    values:
      - DFAT
      - Defence
      - Australian population

  -
    title: Chinese
    color: "dark"
    values:
      - 1.2
      - 1.7
      - 3.7
