title: >
  Figure 14

source: >
  Source: World Governenace Indicators (2022)

#notes: >
  #<b>Notes:</b> data from January 2022

#subtitle: >
  #New cases per million

axes:
  minY: 30
  maxY: 80
  stepsY: 11
  rotateX: true
  percentage: false
  minorLines: true
  dotted: [] # Index of dotted gridlines
  reverse: false
  guideLine: null # value of optional horizontal line. set 'null' if disabled

series:
  -
    title: Year
    values:
      - 2010
      - 2011
      - 2012
      - 2013
      - 2014
      - 2015
      - 2016
      - 2017
      - 2018
  -
    title: Best (East New Britain)
    color: "highlight"
    widen: false
    dashed: false
    values:
      - 76
      - 75
      - 75
      - 75
      - 74
      - 64.5
      - 61
      - 63
      - 58

  -
    title: Province average
    color: "orange"
    widen: false
    dashed: false
    values:
      - 59.55555556
      - 62.94444444
      - 64.30555556
      - 65.775
      - 63
      - 57.6
      - 51.1
      - 50.9
      - 42.6

  -
    title: Worst (Jiwaka)
    color: "grey"
    widen: false
    dashed: false
    values:
      - 30
      - 30
      - 30
      - 65
      - 38
      - 55
      - 33
      - 36
      - 32