title: >

#source: >
  #<b>Source:</b> authors’ calculations based on UN Population Division

subtitle: >

charts:
  - title: Economic model for Indonesia
    subtitle: In your opinion, which one of these countries, if any, do you think should be a model for Indonesia’s future economic development?
    scale:
      minY: 0
      maxY: 30
      datum: 0
      steps: 4

    axes:
      - title: Category
        values:
          - text: Japan
          - text: United States
          - text: China
          - text: Singapore
          - text: Our own model
          - text: Can’t choose
          - text: Malaysia
          - text: Australia
          - text: Other
          - text: India

      - title: "workforce growth"
        values:
          - 26
          - 20
          - 13
          - 12
          - 9
          - 9
          - 3
          - 3
          - 2
          - 1

