title: >
  Average annual countries visited by US and Chinese&nbsp;presidents

source: >
  <b>Source:</b> US Department of State; China's Ministry of Foreign Affairs; People’s Daily.

notes: >
  <b>Notes:</b> Data show the number of different countries visited while in office divided by years in office. Yang Shangkun served as Chinese president from 1988–1993 but only travel from 1989 onwards is included in this dataset.

subtitle: >
  Subtitle goes here

axes:
  minX:  0
  maxX: 10
  stepsX: 11
  percentage: false
  minorLines: true
  dotted: [] # Index of dotted gridlines
  reverse: false

series:
  -
    title: Category
    values:
      - GHW Bush###1989–1993
      - Yang Shangkun###1989–1993
      - Bill Clinton###1993–2001
      - Jiang Zemin###1993–2003
      - GW Bush###2001–2009
      - Hu Jintao###2003–2013
      - Barack Obama###2009–2017
      - Xi Jinping###2013–2019
      - Donald Trump###2017–2019

  -
    title: US presidents
    color: "blue-100"
    values:
      - 9.0
      - 0
      - 9.3
      - 0
      - 9.3
      - 0
      - 7.4
      - 0
      - 8.0

  -
    title: Chinese presidents
    color: "red"
    values:
      - 0
      - 5.5
      - 0
      - 7.2
      - 0
      - 6.9
      - 0
      - 9.7
      - 0
