title: >
  Housing investment share of GDP

#source: >
  #<b>Source:</b> Lorem ipsum

#notes: >
  #<b>Notes:</b> Lorem ipsum

#subtitle: >
  #Real GDP per capita, indexed (2019 = 100)

axes:
  minY:  0
  maxY: 16
  stepsY: 9
  rotateX: false
  percentage: true
  minorLines: true
  dotted: [1,3,5,7,9] # Index of dotted gridlines
  reverse: true
  guideLine: "" # value of optional horizontal line. set 'null' if disabled

series:
  -
    title: Year
    values:
      - 2000
      - 2001
      - 2002
      - 2003
      - 2004
      - 2005
      - 2006
      - 2007
      - 2008
      - 2009
      - 2010
      - 2011
      - 2012
      - 2013
      - 2014
      - 2015
      - 2016
      - 2017
      - 2018
      - 2019	
      - 2020
      - 2021
      - 2022
      - 2023
      - 2024
      - 2025
      - 2026
      - 2027
      - 2028
      - 2029
      - 2030
      - 2031
      - 2032
      - 2033
      - 2034
      - 2035
      - 2036
      - 2037
      - 2038
      - 2039
      - 2040
      - 2041
      - 2042
      - 2043
      - 2044
      - 2045
      - 2046
      - 2047
      - 2048
      - 2049
      - 2050
  -
    title: Actual
    color: "blue-100"
    widen: false
    dashed: false
    dotted: false
    values:
      - 7.15
      - 7.03
      - 6.77
      - 8.58
      - 8.11
      - 9.69
      - 9.58
      - 10.57
      - 9.31
      - 11.92
      - 11.49
      - 14.03
      - 14.34
      - 14.25
      - 13.26
      - 13.19
      - 13.83
      - 13.07
      - 12.84
      - 12.53
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
  -
    title: Baseline growth
    color: "blue-100"
    widen: false
    dashed: true
    dotted: false
    values:
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - 12.52
      - 11.82
      - 11.39
      - 11.03
      - 10.66
      - 10.29
      - 9.90
      - 9.53
      - 9.16
      - 8.79
      - 8.43
      - 8.08
      - 7.57
      - 7.45
      - 7.16
      - 6.89
      - 6.63
      - 6.4
      - 6.19
      - 5.99
      - 5.8
      - 5.62
      - 5.46
      - 5.3
      - 5.16
      - 5.02
      - 4.88
      - 4.76
      - 4.65
      - 4.53
      - 4.43
      - 4.32
      
  -
    title: Best case growth
    color: "blue-100"
    widen: false
    dashed: false
    dotted: true
    values:
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - 12.54
      - 11.83
      - 11.43
      - 11.13
      - 10.83
      - 10.52
      - 10.20
      - 9.91
      - 9.60
      - 9.29
      - 9.00
      - 8.67
      - 8.37
      - 8.08
      - 7.79
      - 7.51
      - 7.22
      - 6.96
      - 6.70
      - 6.44
      - 6.19
      - 5.95
      - 5.71
      - 5.48
      - 5.26
      - 5.04
      - 4.84
      - 4.65
      - 4.47
      - 4.29
      - 4.12
      - 3.96 
