title: >
  Figure 6: China is not yet overly dominant as a creditor

source: >
  Source: authors, government budget documents, International Monetary Fund

notes: >
  * Most recent available figures
charts:
  -
    subtitle: Share of total debt by creditor*, Pacific borrowers
    scale:
      minY: 0
      maxY: 100
      ticks: 6

    legend:
      - China
      - MDBs
      - Other external
      - Private creditors

    colors:
      - "#ff4f1d"
      - "#002a45"
      - "#2D6993"
      - "#539ed4"

    axes:
      -
        title: Year
        values:
          - Tonga
          - Samoa
          - Vanuatu
          - Cook Islands
          - Fiji
          - PNG
      -
        title: Number
        values:
          - [0.564999358, 0.284254335, 0.027860415, 0.122885892]
          - [0.395, 0.477, 0.11, 0.018]
          - [0.323, 0.269, 0.27, 0.138]
          - [0.229027963, 0.742343542, 0.005326232, 0]
          - [0.1, 0.1, 0.08, 0.72,]
          - [0.074181947, 0.194846335, 0.044229492, 0.686742226]
