title: >
  Figure 21: New Ireland’s budget quality scores, 2010–2018

source: >
  Source: NEFC Fiscal Budget Reports (2010 to 2018)

#notes: >
  #<b>Notes:</b> data from January 2022

#subtitle: >
  #New cases per million

axes:
  minY:  0
  maxY: 90
  stepsY: 10
  rotateX: true
  percentage: false
  minorLines: true
  dotted: [] # Index of dotted gridlines
  reverse: false
  guideLine: null # value of optional horizontal line. set 'null' if disabled

series:
  -
    title: Year
    values:
      - 2010
      - 2011
      - 2012
      - 2013
      - 2014
      - 2015
      - 2016
      - 2017
      - 2018
  -
    title: Budget quality score
    color: "highlight"
    widen: false
    dashed: false
    values:
      - 63
      - 54
      - 54.5
      - 76.5
      - 56.5
      - 47
      - 46
      - 37
      - 7