title: >
  Proportion of APS employees with Chinese heritage by agency

source: >
  <b>Sources:</b> Australian Public Service Employment Database; Australian Bureau of Statistics

notes: >
  <b>Abbreviations:</b> Office of National Intelligence (ONI) | Department of the Prime Minister and Cabinet (PM&C) | Department of Foreign Affairs and Trade (DFAT)

subtitle: >
  Total headcount by heritage, December 2019

axes:
  minX: 0
  maxX: 7
  stepsX: 8
  percentage: true
  minorLines: false
  dotted: [] # Index of dotted gridlines
  reverse: true

series:
  -
    title: Department
    values:
      - ONI
      - Attorney-General’s
      - Defence
      - PM&C
      - DFAT
      - Home Affairs
      - Education
      - Austrade
      - Treasury

  -
    title: Chinese
    color: "dark"
    values:
      - 1.6
      - 1.7
      - 1.9
      - 2.1
      - 2.3
      - 2.7
      - 3.7
      - 4.1
      - 5.9
