title: >
  Table 2

table:
  - name: Development
    categories:
      - title: High income
        countries:
          - Australia
          - Austria
          - Bahrain
          - Belgium
          - Canada
          - Chile
          - Croatia
          - Czech Republic
          - Denmark
          - Estonia
          - Finland
          - Germany
          - Greece
          - Hungary
          - Iceland
          - Ireland
          - Israel
          - Italy
          - Japan
          - Kuwait
          - Latvia
          - Lithuania
          - Luxembourg
          - Malta
          - Netherlands
          - New Zealand
          - Norway
          - Panama
          - Poland
          - Portugal
          - Qatar
          - Saudi Arabia
          - Singapore
          - Slovak Republic
          - Slovenia
          - South Korea
          - Spain
          - Sweden
          - Switzerland
          - Taiwan*
          - United Arab Emirates
          - United Kingdom
          - United States
          - Uruguay

      - title: Middle income
        countries:
          - Argentina
          - Belarus
          - Bolivia
          - Brazil
          - Bulgaria
          - China
          - Colombia
          - Costa Rica
          - Côte d'Ivoire
          - Ecuador
          - Ghana
          - India
          - Indonesia
          - Iran
          - Kazakhstan
          - Kenya
          - Malaysia
          - Mexico
          - Morocco
          - Nigeria
          - Pakistan
          - Peru
          - Philippines
          - Romania
          - Russia
          - Senegal
          - Serbia
          - South Africa
          - Thailand
          - Tunisia
          - Turkey
          - Ukraine
          - Vietnam


  - name: Region
    categories:
      - title: Americas
        countries:
          - Argentina
          - Bolivia
          - Brazil
          - Canada
          - Chile
          - Colombia
          - Costa Rica
          - Ecuador
          - Mexico
          - Panama
          - Peru
          - United States
          - Uruguay

      - title: Asia-Pacific
        countries:
          - Australia
          - China
          - India
          - Indonesia
          - Japan
          - Kazakhstan
          - Malaysia
          - New Zealand
          - Pakistan
          - Philippines
          - Russia
          - Singapore
          - South Korea
          - Taiwan*
          - Thailand
          - Vietnam


      - title: Europe
        countries:
          - Austria
          - Belarus
          - Belgium
          - Bulgaria
          - Croatia
          - Czech Republic
          - Denmark
          - Estonia
          - Finland
          - Germany
          - Greece
          - Hungary
          - Iceland
          - Ireland
          - Italy
          - Latvia
          - Lithuania
          - Luxembourg
          - Malta
          - Netherlands
          - Norway
          - Poland
          - Portugal
          - Romania
          - Serbia
          - Slovak Republic
          - Slovenia
          - Spain
          - Sweden
          - Switzerland
          - Ukraine
          - United Kingdom

      - title: Middle East & Africa
        countries:
          - Bahrain
          - Côte d'Ivoire
          - Ghana
          - Iran
          - Israel
          - Kenya
          - Kuwait
          - Morocco
          - Nigeria
          - Qatar
          - Saudi Arabia
          - Senegal
          - South Africa
          - Tunisia
          - Turkey
          - United Arab Emirates


  - name: Politics
    categories:
      - title: Authoritarian
        countries:
          - Bahrain
          - Belarus
          - China
          - Iran
          - Kazakhstan
          - Kuwait
          - Qatar
          - Russia
          - Saudi Arabia
          - United Arab Emirates
          - Vietnam

      - title: Hybrid
        countries:
          - Bolivia
          - Côte d'Ivoire
          - Kenya
          - Morocco
          - Nigeria
          - Pakistan
          - Senegal
          - Turkey
          - Ukraine

      - title: Democratic
        countries:
          - Argentina
          - Australia
          - Austria
          - Belgium
          - Brazil
          - Bulgaria
          - Canada
          - Chile
          - Colombia
          - Costa Rica
          - Croatia
          - Czech Republic
          - Denmark
          - Ecuador
          - Estonia
          - Finland
          - Germany
          - Ghana
          - Greece
          - Hungary
          - Iceland
          - India
          - Indonesia
          - Ireland
          - Israel
          - Italy
          - Japan
          - Latvia
          - Lithuania
          - Luxembourg
          - Malaysia
          - Malta
          - Mexico
          - Netherlands
          - New Zealand
          - Norway
          - Panama
          - Peru
          - Philippines
          - Poland
          - Portugal
          - Romania
          - Serbia
          - Singapore
          - Slovak Republic
          - Slovenia
          - South Africa
          - South Korea
          - Spain
          - Sweden
          - Switzerland
          - Taiwan*
          - Thailand
          - Tunisia
          - United Kingdom
          - United States
          - Uruguay


  - name: Power
    categories:
      - title: Major powers
        countries:
          - China
          - India
          - Japan
          - Russia
          - United Kingdom
          - United States
          - Nigeria
          - Germany
          - Turkey
          - Saudi Arabia
          - South Africa
          - Iran

      - title: Middle powers
        countries:
          - Argentina
          - Australia
          - Brazil
          - Canada
          - Colombia
          - Ghana
          - Indonesia
          - Israel
          - Italy
          - Kenya
          - Malaysia
          - Mexico
          - Morocco
          - Pakistan
          - Philippines
          - Poland
          - South Korea
          - Spain
          - Taiwan*
          - Thailand
          - Ukraine
          - United Arab Emirates
          - Vietnam

      - title: Minor powers
        countries:
          - Austria
          - Bahrain
          - Belarus
          - Belgium
          - Bolivia
          - Bulgaria
          - Chile
          - Costa Rica
          - Côte d'Ivoire
          - Croatia
          - Czech Republic
          - Denmark
          - Ecuador
          - Estonia
          - Finland
          - Greece
          - Hungary
          - Iceland
          - Ireland
          - Kazakhstan
          - Kuwait
          - Latvia
          - Lithuania
          - Luxembourg
          - Malta
          - Netherlands
          - New Zealand
          - Norway
          - Panama
          - Peru
          - Portugal
          - Qatar
          - Romania
          - Senegal
          - Serbia
          - Singapore
          - Slovak Republic
          - Slovenia
          - Sweden
          - Switzerland
          - Tunisia
          - Uruguay


  - name: Population
    categories:
      - title: Large
        countries:
          - Brazil
          - China
          - India
          - Indonesia
          - Japan
          - Mexico
          - Nigeria
          - Pakistan
          - Philippines
          - Russia
          - United States

      - title: Medium
        countries:
          - Argentina
          - Australia
          - Belgium
          - Bolivia
          - Canada
          - Chile
          - Colombia
          - Côte d'Ivoire
          - Czech Republic
          - Ecuador
          - Germany
          - Ghana
          - Greece
          - Iran
          - Italy
          - Kazakhstan
          - Kenya
          - Malaysia
          - Morocco
          - Netherlands
          - Peru
          - Poland
          - Portugal
          - Romania
          - Saudi Arabia
          - Senegal
          - South Africa
          - South Korea
          - Spain
          - Sweden
          - Taiwan*
          - Thailand
          - Tunisia
          - Turkey
          - Ukraine
          - United Kingdom
          - Vietnam

      - title: Small
        countries:
          - Austria
          - Bahrain
          - Belarus
          - Bulgaria
          - Costa Rica
          - Croatia
          - Denmark
          - Estonia
          - Finland
          - Hungary
          - Iceland
          - Ireland
          - Israel
          - Kuwait
          - Latvia
          - Lithuania
          - Luxembourg
          - Malta
          - New Zealand
          - Norway
          - Panama
          - Qatar
          - Serbia
          - Singapore
          - Slovak Republic
          - Slovenia
          - Switzerland
          - United Arab Emirates
          - Uruguay
