title: >
  Trust in global powers

#source: >
  #<b>Source:</b> Lorem ipsum

#notes: >
  #<b>Notes:</b> Lorem ipsum

subtitle: >
  How much do you trust the following countries to act responsibly in the world?

axes:
  minY: 30
  maxY: 90
  stepsY: 7
  rotateX: false
  percentage: true
  minorLines: true
  dotted: [1,3,5,7,9] # Index of dotted gridlines
  reverse: true
  guideLine: "" # value of optional horizontal line. set 'null' if disabled

series:
  -
    title: Year
    values:
      - 2006
      - 2011
      - 2021
  -
    title: Indonesia
    color: "teal"
    widen: false
    dashed: false
    dotted: false
    values:
      - null
      - 86
      - 84
  -
    title: United States
    color: "orange"
    widen: false
    dashed: false
    dotted: false
    values:
      - 32
      - 72
      - 56 
  -
    title: Japan
    color: "grey"
    widen: false
    dashed: false
    dotted: false
    values:
      - 76
      - 80
      - 65
  -
    title: Australia
    color: "yellow"
    widen: false
    dashed: false
    dotted: false
    values:
      - null
      - 75
      - 55
  -
    title: China
    color: "red"
    widen: false
    dashed: false
    dotted: false
    values:
      - 59
      - 60
      - 42
  -
    title: Singapore
    color: "green"
    widen: false
    dashed: false
    dotted: false
    values:
      - null
      - 69
      - 66
  -
    title: India
    color: "dark"
    widen: false
    dashed: false
    dotted: false
    values:
      - 58
      - 51
      - 41
  -
    title: Vietnam
    color: "red-dark"
    widen: false
    dashed: false
    dotted: false
    values:
      - null
      - 38
      - 39
  -
    title: United Kingdom
    color: "grey-200"
    widen: false
    dashed: false
    dotted: false
    values:
      - null
      - null
      - 59
  -
    title: Russia
    color: "purple"
    widen: false
    dashed: false
    dotted: false
    values:
      - null
      - null
      - 47
  -
    title: South Korea
    color: "highlight"
    widen: false
    dashed: false
    dotted: false
    values:
      - null
      - null
      - 53