title: >
  Graph 4: Inbound remittances as a percentage of national income

source: >
  Source: The World Bank

#notes: >
  #<b>Notes:</b> Lorem ipsum

subtitle: >
  2021

axes:
  minX:  0
  maxX: 50
  stepsX: 11
  percentage: true
  minorLines: true
  dotted: [1,3,5,7,9,11,13] # Index of dotted gridlines
  reverse: false

series:
  -
    title: Category
    values:
      - Tuvalu
      - Kiribati
      - Fiji
      - Marshall Is.
      - Vanuatu
      - Samoa
      - Tonga

  -
    title: Series 1
    color: "dark"
    values:
      - 4.2
      - 5.9
      - 9.2
      - 13.3
      - 21.4
      - 29.4
      - 46.2
