title: >
  Figure 7: Most Chinese loans look sustainable but not all

notes: >
  Note: 1. For Fiji, Palau, and Nauru, the IMF uses a ratings system for
  higher-income countries where it simply rates their debt outlook as
  “sustainable” or “unsustainable”

source: >
  Source: Authors’ calculations; Lowy Institute Pacific Aid Map; IMF; World Bank

charts:
  -
    title: Most Chinese loans look sustainable but not all
    subtitle: Share of total loans by creditor and borrower IMF debt rating
    scale:
      minY:  0
      maxY: 0.8
      ticks: 5

    colors:
      - "#16b56f"
      - "#ffae00"
      - "#ff1f2f"
      - "#002a45"
      - "#b7c1ce"

    legend:
      - Low risk
      - Moderate risk
      - High risk
      - Sustainable<sup>1</sup>
      - No rating

    axes:
      -
        title: Lenders
        values:
          - ADB
          - World Bank Group
          - Japan
          - China
          - Taiwan
      -
        title: Risk
        values:
          - [0.366328116, 0.454167015, 0.012107212, 0.068748972, 0.098648686]
          - [0.456632638, 0.363491969, 0, 0.179875392, 0]
          - [0.547764794, 0.452235206, 0, 0, 0]
          - [0.460180851, 0.174554706, 0.100513555, 0.26015253, 0.004598357]
          - [0, 0, 0.695927262, 0.304072738, 0]
