title: >
  Line chart

source: >
  <b>Source:</b> Lorem ipsum

notes: >
  <b>Notes:</b> Lorem ipsum

subtitle: >
  Subtitle goes here

axes:
  minY:  -1
  maxY: 2
  stepsY: 7
  rotateX: false
  percentage: true
  minorLines: false
  dotted: [] # Index of dotted gridlines
  reverse: false
  guideLine: null # value of optional horizontal line. set 'null' if disabled

series:
  -
    title: Year
    values:
      - China (2019)	
      - Korea (1980)	
      - Taiwan (1975)

  -
    title: Series 1
    color: "dark"
    widen: false
    dashed: true
    values:
      - -1
      - 0
      - 1
      - 1.5
      - 2

  -
    title: Series 2
    color: "highlight"
    widen: true
    dashed: false
    values:
      - 0
      - 0.5
      - 1
      - 1.5
      - 2

  -
    title: Series 3
    color: "red"
    widen: false
    dashed: false
    values:
      - 2
      - 1.5
      - 1
      - 0.5
      - 0
