title: >
  Grouped bar chart

source: >
  <b>Source:</b> Lorem ipsum

notes: >
  <b>Notes:</b> Lorem ipsum

subtitle: >
  Subtitle goes here

axes:
  minY:  0
  maxY: 4
  stepsY: 5
  rotateX: false
  percentage: false
  minorLines: true
  dotted: [1, 3] # Index of dotted gridlines

series:
  -
    title: Pandemic performance
    values:
      - 1971
      - 1972
      - 1973
      - 1974
      - 1975
      - 1976
      - 1977
      - 1978
      - 1979
      - 1980
      - 1981
      - 1982
      - 1983
      - 1984
      - 1985
      - 1986
      - 1987
      - 1988
      - 1989
      - 1990
      - 1991
      - 1992
      - 1993
      - 1994
      - 1995
      - 1996
      - 1997
      - 1999
      - 2000
      - 2001
      - 2002
      - 2003
      - 2004
      - 2005
      - 2006
      - 2007
      - 2008
      - 2009
      - 2010
      - 2011
      - 2012
      - 2013
      - 2014
      - 2015
      - 2016
      - 2017
      - 2018
      - 2019
      - 2020
      - 2021
      - 2022
  -
    title: China
    color: "red"
    values:
      - 0
      - 0.2
      - 0.25
      - 0.2
      - 0.2
      - 0.2
      - 0.2
      - 0.2
      - 0.333333333
      - 0.333333333
      - 0.333333333
      - 0.333333333
      - 0.333333333
      - 0.333333333
      - 0.333333333
      - 0.333333333
      - 0.333333333
      - 0.333333333
      - 0.333333333
      - 0.333333333
      - 0.333333333
      - 0.5
      - 0.5
      - 0.5
      - 0.5
      - 0
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 0.5
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
  -
    title: France
    color: "lime"
    values:
      - 1
      - 1
      - 0.5
      - 0.5
      - 0.5
      - 0.5
      - 0.5
      - 0.333333333
      - 0.333333333
      - 0.333333333
      - 0.333333333
      - 0.333333333
      - 0.333333333
      - 0.333333333
      - 0.333333333
      - 0.333333333
      - 0.333333333
      - 0.333333333
      - 0.333333333
      - 0.333333333
      - 0.333333333
      - 0.5
      - 1
      - 1
      - 1
      - 1
      - 2
      - 2
      - 2
      - 1.5
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
  -
    title: Russian Federation
    color: "green"
    values:
      - 0.333333333
      - 0.2
      - 0.25
      - 0.2
      - 0.2
      - 0.2
      - 0.2
      - 0.2
      - 0.166666667
      - 0.166666667
      - 0.166666667
      - 0.166666667
      - 0.166666667
      - 0.166666667
      - 0.166666667
      - 0.142857143
      - 0.2
      - 0.2
      - 0.25
      - 0.25
      - 0.25
      - 0.333333333
      - 0.75
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1.5
      - 1.5
      - 1
      - 1
      - 1
      - 1
      - 1
      - 2
      - 2
      - 2.5
      - 2.5
      - 2
      - 2
  -
    title: UK
    color: "highlight"
    values:
      - 1
      - 0
      - 0
      - 0.2
      - 0.2
      - 0.2
      - 0.2
      - 0.2
      - 0.166666667
      - 0.166666667
      - 0.166666667
      - 0.166666667
      - 0.166666667
      - 0.166666667
      - 0.166666667
      - 0.285714286
      - 0.7
      - 1.2
      - 1.25
      - 1.25
      - 1.25
      - 1.5
      - 0.75
      - 0.333333333
      - 1.333333333
      - 1
      - 1
      - 1
      - 1.5
      - 2
      - 2
      - 2
      - 2
      - 2
      - 3
      - 1.5
      - 1.5
      - 2
      - 1.5
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1.5
      - 2
      - 1.5
      - 1
      - 1
      - 1
  -
    title: USA
    color: "pink"
    values:
      - 2
      - 2.2
      - 2.25
      - 2.2
      - 2.2
      - 2.7
      - 2.7
      - 2.2
      - 2.166666667
      - 2.166666667
      - 2.166666667
      - 2.166666667
      - 2.166666667
      - 2.166666667
      - 2.166666667
      - 2.142857143
      - 2.2
      - 2.2
      - 2.25
      - 2.25
      - 2.25
      - 3.5
      - 4
      - 4
      - 3.666666667
      - 4
      - 4
      - 4
      - 3.5
      - 3
      - 3
      - 3
      - 3
      - 3
      - 3
      - 3
      - 3.5
      - 4
      - 4
      - 4
      - 4
      - 4
      - 4
      - 3.5
      - 3
      - 3
      - 3
      - 3
      - 3.5
      - 4
      - 4
      - 4