title: >
  Imports to the Philippines

source: >
  <strong>Source:</strong> Lowy Institute (<a href="https://power.lowyinstitute.org/" target="_blank">2023 Asia Power Index</a>)

#notes: >
  #<b>Notes:</b> Lorem ipsum

subtitle: >
  From China and the United States

axes:
  minY:  0
  maxY: 70
  stepsY: 8
  rotateX: false
  percentage: false
  minorLines: true
  dotted: [1,2,3,4,5,6,7,8] # Index of dotted gridlines

series:
  -
    title: Exports from the Philippines
    values:
      - 2015
      - 2021
  -
    title: China
    color: "red"
    values:
      - 13.93
      - 61.85
  -
    title: United States
    color: "highlight"
    values:
      - 7.94
      - 9.27
