title: >
  COVID-19 vaccine doses delivered to the&nbsp;region

subtitle: >
  Donations per capita

source: >
  Sources: <a href="https://www.thinkglobalhealth.org/article/billions-committed-millions-delivered">Think Global Health</a>, <a href="https://data.worldbank.org/indicator/SP.POP.TOTL">World Bank</a> and author’s calculations.

notes: >
  * Reflects vaccine donation data as of 28 October 2021

axes:
  minX: 0
  maxX: 0.3
  stepsX: 4
  percentage: false
  minorLines: true
  dotted: [] # Index of dotted gridlines
  reverse: false

series:
  - title: Category
    values:
      - United States
      - Japan
      - New Zealand
      - Australia
      - Singapore
      # - South Korea
      # - China
      # - Cambodia
      # - India

  - title: Series 1
    color: "white"
    values:
      - 0.280003362
      - 0.194493434
      - 0.168964816
      - 0.124102346
      - 0.063959952
      # - 0.030362162
      # - 0.02787192
      # - 0.012131107
      # - 0.004939924
