title: >
  Diplomatic Meetings

source: >
  <b>Source:</b> Lowy Institute (<a href="https://power.lowyinstitute.org/" target="_blank">2023 Asia Power Index</a>)

notes: >
  Y-axis: Diversity - Percentage regional countries with whom at least one activity was held

subtitle: >
  Leader and foreign minister (2022)

axes:
  xLabel: Number of meetings held with regional counterparts
  minX:  0
  maxX: 100
  stepsX: 11
  rotateX: false
  interceptX: null # value of optional vertical line. set 'null' if disabled
  percentageX: false
  gridX: true

  yLabel: Diversity
  minY:  0
  maxY: 100
  stepsY: 11
  interceptY: null # value of optional horizontal line. set 'null' if disabled
  percentageY: true
  gridY: true

  rScaleFactor: 10


# Data format: [x, y, r]
series:
  -
    title: Series 1
    color: dark
    names:
      - [ Australia ]
      - [ Bangladesh ]
      - [ Bhutan ]
      - [ Brunei ]
      - [ Cambodia ]
      - [ China ]
      - [ India ]
      - [ Indonesia ]
      - [ Japan ]
      - [ Laos ]
      - [ Malaysia ]
      - [ Maldives ]
      - [ Mongolia ]
      - [ Myanmar ]
      - [ Nepal ]
      - [ New Zealand ]
      - [ Pakistan ]
      - [ Papua New Guinea ]
      - [ Philippines ]
      - [ Russia ]
      - [ Singapore ]
      - [ South Korea ]
      - [ Sri Lanka ]
      - [ Thailand ]
      - [ Timor-Leste ]
      - [ United States ]
      - [ Vietnam ]

    values:
      - [78, 73.0769231, 1.0 ]
      - [29, 73.0769231, 1.0 ]
      - [6, 15.3846154, 1.0 ]
      - [35, 69.2307692, 1.0 ]
      - [59, 84.6153846, 1.0 ]
      - [96, 96.1538462, 1.0 ]
      - [74, 80.7692308, 1.0 ]
      - [81, 88.4615385, 1.0 ]
      - [90, 84.6153846, 1.0 ]
      - [38, 57.6923077, 1.0 ]
      - [27, 53.8461538, 1.0 ]
      - [24, 57.6923077, 1.0 ]
      - [16, 30.7692308, 1.0 ]
      - [10, 19.2307692, 1.0 ]
      - [7, 19.2307692, 1.0 ]
      - [33, 65.3846154, 1.0 ]
      - [32, 50, 1.0 ]
      - [17, 38.4615385, 1.0 ]
      - [32, 61.5384615, 1.0 ]
      - [39, 53.8461538, 1.0 ]
      - [68, 84.6153846, 1.0 ]
      - [52, 73.0769231, 1.0 ]
      - [26, 69.2307692, 1.0 ]
      - [45, 80.7692308, 1.0 ]
      - [27, 53.8461538, 1.0 ]
      - [67, 65.3846154, 1.0 ]
      - [68, 76.9230769, 1.0 ]