title: >
  Debt and deficit as a share of GDP, debt service as a share of own revenue, 1976–2022

source: >
  Source: <a href="https://devpolicy.org/pngeconomic/series/fiscal-data/">PNG Economics database</a>; <a href="http://www.treasury.gov.pg/html/national_budget/files/2023/2022 FBO Report.pdf">2022 Final Budget Outcome</a>


#notes: >
  #<b>Notes:</b> data from January 2022

#subtitle: >
  #New cases per million

axes:
  minY:  -10
  maxY: 60
  stepsY: 8
  rotateX: true
  percentage: true
  minorLines: true
  dotted: [] # Index of dotted gridlines
  reverse: false
  guideLine: null # value of optional horizontal line. set 'null' if disabled

series:
  -
    title: Year
    values:
      - 1976
      - 1977
      - 1978
      - 1979
      - 1980
      - 1981
      - 1982
      - 1983
      - 1984
      - 1985
      - 1986
      - 1987
      - 1988
      - 1989
      - 1990
      - 1991
      - 1992
      - 1993
      - 1994
      - 1995
      - 1996
      - 1997
      - 1998
      - 1999
      - 2000
      - 2001
      - 2002
      - 2003
      - 2004
      - 2005
      - 2006
      - 2007
      - 2008
      - 2009
      - 2010
      - 2011
      - 2012
      - 2013
      - 2014
      - 2015
      - 2016
      - 2017
      - 2018
      - 2019
      - 2020
      - 2021
      - 2022
  -
    title: Debt/GDP
    color: "highlight"
    widen: false
    dashed: false
    values:
      - 17
      - 18
      - 16
      - 17
      - 19
      - 21
      - 25
      - 25
      - 27
      - 30
      - 30
      - 28
      - 24
      - 26
      - 30
      - 29
      - 30
      - 32
      - 35
      - 36
      - 37
      - 41
      - 44
      - 44
      - 38
      - 45
      - 47
      - 39
      - 37
      - 32
      - 26
      - 22
      - 22
      - 22
      - 18
      - 17
      - 19
      - 25
      - 27
      - 30
      - 34
      - 32
      - 37
      - 40
      - 47
      - 52
      - 50
  -
    title: Debt serivice as a share of own revenue
    color: "orange"
    widen: false
    dashed: false
    values:
      - 8
      - 11
      - 8
      - 10
      - 7
      - 14
      - 16
      - 16
      - 15
      - 14
      - 15
      - 12
      - 12
      - 11
      - 15
      - 14
      - 16
      - 14
      - 15
      - 18
      - 15
      - 16
      - 18
      - 19
      - 17
      - 18
      - 17
      - 25
      - 11
      - 8
      - 6
      - 6
      - 6
      - 8
      - 5
      - 5
      - 5
      - 6
      - 8
      - 11
      - 14
      - 16
      - 16
      - 18
      - 20
      - 19
      - 15
  -
    title: Deficit/GDP
    color: "grey"
    widen: false
    dashed: false
    values:
      - 1
      - 1
      - 1
      - 3
      - 1
      - 4
      - 4
      - 2
      - 1
      - 1
      - 2
      - 1
      - 1
      - 1
      - 2
      - 3
      - 4
      - 4
      - 2
      - 0
      - 0
      - 0
      - 1
      - 2
      - 2
      - 2
      - 3
      - 1
      - -1
      - -2
      - -4
      - -6
      - -2
      - 6
      - -1
      - 1
      - 1
      - 7
      - 6
      - 5
      - 5
      - 3
      - 3
      - 5
      - 9
      - 7
      - 5