title: >
  Domestic doses administered* to doses delivered abroad

subtitle: >
  Ratio, top 20 countries by pledge or actual donation

source: >
  <b>Source:</b> <em><a target="_blank" href="https://www.thinkglobalhealth.org/article/billions-committed-millions-delivered">Think Global Health</a></em>, <em><a target="_blank" href="https://github.com/owid/covid-19-data/tree/master/public/data">Our World in Data</a></em>, <em><a target="_blank" href="https://indopacifichealthsecurity.dfat.gov.au/vaccine-sharing">Australian Department of Foreign Affairs and Trade</a></em> and authors’ calculations 

notes: >
  * Latest data available as of 15 October 2021

axes:
  minX:  0
  maxX: 90
  stepsX: 10
  percentage: false
  minorLines: true
  dotted: [] # Index of dotted gridlines
  reverse: true

series:
  -
    title: Category
    values:
      - United States
      - Austria
      - UAE
      - Denmark
      - Japan
      - Norway
      - Australia
      - Sweden
      - United Kingdom
      - France
      - Spain
      - Portugal
      - Canada
      - Belgium
      - Germany
      - Italy
      - China
      - India
      - Switzerland
      - Finland

  -
    title: Series 1
    color: "grey-interpreter"
    values:
      - 2.717749824
      - 5.258452061
      - 6.360003416
      - 7.017072277
      - 7.626873947
      - 8.300656425
      - 8.767665841
      - 10.67586753
      - 11.24078692
      - 13.51168557
      - 16.49136182
      - 16.79323253
      - 19.68460377
      - 19.82953014
      - 30.4159033
      - 34.24885396
      - 44.63754788
      - 89.51020754
      - 0
      - 0
