title: >
  China’s exports to Central Asia of vehicles and parts other than railway or tramway rolling stock

source: >
  <b>Source:</b> UN Comtrade, PRC General Administration of Customs, Author’s Calculations

#notes: >
  #<b>Notes:</b> Lorem ipsum

subtitle: >
  Millions, USD

axes:
  minY:  0
  maxY: 900
  stepsY: 10
  rotateX: true
  percentage: false
  minorLines: true
  dotted: [1, 3] # Index of dotted gridlines

series:
  -
    title: Month
    values:
      - January
      - February
      - March
      - April
      - May
      - June
      - July
      - August
      - September
      - October
      - November
      - December

  -
    title: 2019
    color: "grey-interpreter"
    values:
      - 73.27
      - 56.32
      - 97.14
      - 142.49
      - 126.46
      - 158.02
      - 130.73
      - 95.74
      - 168.33
      - 100.5
      - 117.09
      - 157.34
  -
    title: 2020
    color: "grey-400"
    values:
      - 87.5
      - 8.31
      - 21.32
      - 47.75
      - 91.46
      - 143.1
      - 156.29
      - 111.04
      - 124.61
      - 144.55
      - 95.12
      - 113.87
  -
    title: 2021
    color: "yellow-light"
    values:
      - 103.73
      - 59.63
      - 107.58
      - 113.82
      - 113.13
      - 192.61
      - 178.78
      - 139.02
      - 111.66
      - 73.62
      - 107.11
      - 195
  -
    title: 2022
    color: "yellow"
    values:
      - 193.17
      - 161.62
      - 261.75
      - 251.44
      - 212.48
      - 262.56
      - 219.01
      - 257.91
      - 223.57
      - 231.16
      - 268.6
      - 343.38
  -
    title: 2023
    color: "orange"
    values:
      - 357.77
      - 406.21
      - 598.69
      - 662.69
      - 802.58
