title: >
  Trust in sources of information

subtitle: >
  To what extent do you trust the following to be an accurate and fair source of
  information?

axes:
  minX: 0
  maxX: 100
  stepsX: 6
  percentage: true
  minorLines: true
  dotted: [1, 3, 5, 7, 9, 11, 13] # Index of dotted gridlines
  reverse: false

series:
  - title: Category
    values:
      - Military/armed forces
      - Indonesian President, Joko Widodo
      - Scientists or experts
      - Friends and family
      - Religious organisations/leaders
      - Police
      - Local government
      - Civil society groups
      - Television and radio news
      - Foreign or international media
      - Political elites/parties
      - Newspapers and online news websites
      - Influencers and celebrities

  - title: A great deal
    color: "blue-100"
    values:
      - 53
      - 53
      - 30
      - 29
      - 27
      - 32
      - 26
      - 19
      - 20
      - 15
      - 22
      - 15
      - 11

  - title: Somewhat
    color: "highlight"
    values:
      - 41
      - 39
      - 60
      - 59
      - 60
      - 49
      - 55
      - 61
      - 59
      - 54
      - 46
      - 52
      - 45

  - title: Not very much
    color: "orange-light"
    values:
      - 5
      - 7
      - 9
      - 10
      - 12
      - 16
      - 17
      - 19
      - 20
      - 27
      - 28
      - 31
      - 38

  - title: Not at all
    color: "orange"
    values:
      - 1
      - 1
      - 1
      - 1
      - 1
      - 3
      - 3
      - 1
      - 2
      - 3
      - 5
      - 3
      - 6
