title: >
  Figure 1: Business investment

source: >
  <b>Source:</b> Australian Bureau of Statistics

notes: >
  <b>Notes:</b> ???

charts:
  -
    title: >
      A. Business investment as a share of GDP
    subtitle: ""
    scale:
      ticks: 11
      minY: 0
      maxY: 20
    legend:
      - Total
    colors:
      - "#002a45"
    axes:
      -
        title: Years
        values:
          - 1988
          - 1989
          - 1990
          - 1991
          - 1992
          - 1993
          - 1994
          - 1995
          - 1996
          - 1997
          - 1998
          - 1999
          - 2000
          - 2001
          - 2002
          - 2003
          - 2004
          - 2005
          - 2006
          - 2007
          - 2008
          - 2009
          - 2010
          - 2011
          - 2012
          - 2013
          - 2014
          - 2015
          - 2016
          - 2017
          - 2018
          - 2019

      -
        title: |
          %
        values:
          - [7.56]
          - [8.13]
          - [7.22]
          - [6.25]
          - [6.11]
          - [6.27]
          - [6.9]
          - [7.53]
          - [8.17]
          - [8.48]
          - [8.76]
          - [8.77]
          - [8.83]
          - [8.51]
          - [9.35]
          - [10.3]
          - [10.96]
          - [12.16]
          - [12.84]
          - [13.8]
          - [14.71]
          - [13.86]
          - [13.43]
          - [15.51]
          - [17.69]
          - [16.8]
          - [15.55]
          - [13.72]
          - [12.02]
          - [12.25]
          - [12.13]
          - [11.84]

  -
    title: >
      B. Business investment: Non-mining
    subtitle: ""
    scale:
      ticks: 11
      minY: 80
      maxY: 180
    legend:
      - Non-mining
    colors:
      - "#539ed4"
    axes:
      -
        title: Years
        values:
          - 2002
          - 2003
          - 2004
          - 2005
          - 2006
          - 2007
          - 2008
          - 2009
          - 2010
          - 2011
          - 2012
          - 2013
          - 2014
          - 2015
          - 2016
          - 2017
          - 2018
          - 2019
      -
        title: |
          $B
        values:
          - [82.746]
          - [93.762]
          - [106.283]
          - [117.495]
          - [119.373]
          - [133.314]
          - [139.960]
          - [133.962]
          - [131.933]
          - [137.004]
          - [130.923]
          - [128.029]
          - [135.476]
          - [139.888]
          - [138.426]
          - [152.272]
          - [164.707]
          - [165.635]
