title: >
  Figure 1: China likely will not pull much ahead of the US

source: >
  <b>Source:</b> authors' projections, IMF World Economic Outlook October 2021, and OECD Long-Term Growth Forecasts (2018)

#notes: >
  #<b>Notes:</b> Lorem ipsum

subtitle: >
  China's GDP relative to US, baseline projection in nominal USD

axes:
  minY:  0
  maxY: 140
  stepsY: 8
  rotateX: false
  percentage: true
  minorLines: true
  dotted: [1,3,5,7,9] # Index of dotted gridlines
  reverse: true
  guideLine: "" # value of optional horizontal line. set 'null' if disabled

series:
  -
    title: Year
    values:
      - 2000
      - 2001
      - 2002
      - 2003
      - 2004
      - 2005
      - 2006
      - 2007
      - 2008
      - 2009
      - 2010
      - 2011
      - 2012
      - 2013
      - 2014
      - 2015
      - 2016
      - 2017
      - 2018
      - 2019	
      - 2020
      - 2021
      - 2022
      - 2023
      - 2024
      - 2025
      - 2026
      - 2027
      - 2028
      - 2029
      - 2030
      - 2031
      - 2032
      - 2033
      - 2034
      - 2035
      - 2036
      - 2037
      - 2038
      - 2039
      - 2040
      - 2041
      - 2042
      - 2043
      - 2044
      - 2045
      - 2046
      - 2047
      - 2048
      - 2049
      - 2050
  -
    title: Actual
    color: "highlight"
    widen: false
    dashed: false
    dotted: false
    values:
      - 12
      - 13
      - 13
      - 14
      - 16
      - 18
      - 20
      - 25
      - 31
      - 35
      - 40
      - 48
      - 53
      - 57
      - 60
      - 61
      - 60
      - 63
      - 67
      - 67
      - 71
      - 74
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
  -
    title: Projected
    color: "highlight"
    widen: false
    dashed: false
    dotted: true
    values:
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - 74
      - 74
      - 77
      - 81
      - 85
      - 88
      - 92
      - 95
      - 98
      - 101
      - 103
      - 104
      - 106
      - 107
      - 108
      - 109
      - 110
      - 111
      - 112
      - 113
      - 113
      - 114
      - 114
      - 114
      - 115
      - 115
      - 115
      - 115
      - 115
      - 115
  