title: >
  Diplomatic dialogues (bilateral)

source: >
  Source: Lowy Institute 2023 Asia Power Index

#notes: >
  #<b>Notes:</b> Lorem ipsum

subtitle: >
  The five most active Asia Power Index countries in bilateral diplomacy between leaders or foreign ministers (2021)

axes:
  minY:  0
  maxY: 80
  stepsY: 9
  rotateX: false
  percentage: false
  minorLines: true
  dotted: [] # Index of dotted gridlines

series:
  -
    title: Country
    values:
      - China
      - United States
      - Australia
      - Indonesia
      - South Korea
      
  -
    title: Number
    color: "dark"
    values:
      - 46
      - 40
      - 36
      - 30
      - 29
