title: >
  Figure 8: UN Security Council passed and vetoed resolutions 

#source: >
  #<b>Source:</b> Lorem ipsum

#notes: >
  #<b>Notes:</b> Lorem ipsum

subtitle: >
  Total passed and vetoed by permanent members, 1971–Sept 2022

axes:
  minY:  0
  maxY: 100
  stepsY: 11
  rotateX: false
  percentage: false
  minorLines: true
  dotted: [] # Index of dotted gridlines
  reverse: false

series:
  -
    title: Year
    values:
      - 1970
      - 1971
      - 1972
      - 1973
      - 1974
      - 1975
      - 1976
      - 1977
      - 1978
      - 1979
      - 1980
      - 1981
      - 1982
      - 1983
      - 1984
      - 1985
      - 1986
      - 1987
      - 1988
      - 1989
      - 1990
      - 1991
      - 1992
      - 1993
      - 1994
      - 1995
      - 1996
      - 1997
      - 1998
      - 1999
      - 2000
      - 2001
      - 2002
      - 2003
      - 2004
      - 2005
      - 2006
      - 2007
      - 2008
      - 2009
      - 2010
      - 2011
      - 2012
      - 2013
      - 2014
      - 2015
      - 2016
      - 2017
      - 2018
      - 2019
      - 2020
      - 2021
      - 2022

  -
    title: Resolutions vetoed
    color: "teal-light"
    values:
      - 1
      - 4
      - 7
      - 3
      - 2
      - 6
      - 7
      - 3
      - .01
      - 2
      - 3
      - 5
      - 8
      - 3
      - 3
      - 7
      - 8
      - 2
      - 6
      - 5
      - 2
      - .01
      - .01
      - 1
      - 1
      - 1
      - 1
      - 3
      - .01
      - 1
      - .01
      - 2
      - 2
      - 2
      - 3
      - .01
      - 2
      - 1
      - 1
      - 1
      - .01
      - 2
      - 2
      - .01
      - 2
      - 2
      - 2
      - 6
      - 3
      - 3
      - 3
      - 1
      - 3
  -
    title: Resolutions passed
    color: "blue-100"
    values:
      - 16
      - 16
      - 17
      - 20
      - 22
      - 18
      - 18
      - 20
      - 21
      - 18
      - 23
      - 15
      - 29
      - 17
      - 14
      - 21
      - 13
      - 13
      - 20
      - 20
      - 37
      - 42
      - 74
      - 93
      - 77
      - 66
      - 57
      - 54
      - 73
      - 65
      - 50
      - 52
      - 68
      - 67
      - 59
      - 71
      - 87
      - 56
      - 65
      - 48
      - 59
      - 66
      - 53
      - 47
      - 63
      - 64
      - 77
      - 61
      - 54
      - 51
      - 57
      - 57
      - 33
  

